---
title: "Exam Template"
author: "Nick Thompson"
date: "10/10/2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
cat("\014")
# devtools::install_github("chrismeserole/obsval")
library(foreign)
library(stargazer)
library(devtools)
library(obsval)
library(mvtnorm)
library(arm)
library(vioplot)
library(lmtest)
library(knitr)
```

# Introduction:

```{r cars, echo=FALSE}
n <- 1000
educate <- rnorm(n)
age <- rnorm(n)
income<-rnorm(n)
X <- cbind(1,educate,age,income)
b <- c(1,1,-2,2)
p <- plogis(X%*%b)
vote <- rbinom(n, 1, p)
# estimate simple logit model
m <- glm(vote ~ educate + age + income, family = binomial)
# display results
display(m, detail = TRUE)
```
```{r, stargazer, results='asis'}
stargazer(m, header = F)

```

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=TRUE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
