---
title: "Exam Template"
author: "Nick Thompson"
date: "10/10/2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
cat("\014")
# devtools::install_github("chrismeserole/obsval")
library(foreign)
library(stargazer)
library(devtools)
library(obsval)
library(mvtnorm)
library(arm)
library(vioplot)
library(lmtest)
library(knitr)
library(readstata13)
library(ggplot2)
```

Pull in Data

```{r}
setwd("~/Documents/GitHubRepo/729_Reed_MLE_git/Exam")
#voterid <- read.csv(file = "https://raw.githubusercontent.com/Neilblund/729A/master/data/voterid.csv", header = TRUE, sep = ",")
#data <- read.dta(file = "https://raw.githubusercontent.com/Neilblund/729A/master/data/voterid.csv")
#data <- read.dta13(file = "https//raw.githubusercontent.com/Neilblund/729A/master/data/voterid.csv")
#save(voterid, file = "data.RData")
load("data.RData")
#View(voterid2)
```

# Introduction:

```{r cars, echo=FALSE}


```

Logit

```{r logit link, echo=TRUE}

```

Probit

```{r probit link, echo=FALSE}
#descriptive statistics for all variables
#stargazer(voterid, type = 'text')
# run probit, show results
voterid2 <- na.omit(voterid)
#View(voterid2)
voterid2$mean_gopleg <- mean(voterid2$gopleg)
voterid2$sd_gopleg <- 0.5*sd(voterid2$gopleg)
voterid2$med_g = median(voterid2$gopleg)
```

```{r stargazer1, echo=TRUE, results='asis'}
stargazer(voterid2, header = F)
```

```{r plot, echo=T}
g <- ggplot(voterid2,aes(x=gopleg))
g + geom_histogram(aes(y=..density..),binwidth = 7.5) +
  geom_density() +
  geom_vline(xintercept = voterid2$mean_gopleg,linetype='longdash') +
  geom_vline(xintercept = voterid2$med_g)
gopleg_obs_low <- voterid2$mean_gopleg - voterid2$sd_gopleg
gopleg_obs_high <- voterid2$mean_gopleg + voterid2$sd_gopleg


# run probit, show results
(model_1 <- glm('photo ~ fraud + election_margin + gopleg', 
               family = binomial(link = "probit"), 
               data = voterid2)) 

summary(model_1)
#stargazer(model_1,type = 'text')

# generate predicted probabilities automatically
voterid2$pprob <- predict(model_1,type="response")

# generate predicted probabilities manually
voterid2$pprob_manual <- pnorm(model_1$coef['(Intercept)'] +
                                 model_1$coef['fraud']*voterid2$fraud +
                                 model_1$coef['election_margin']*voterid2$election_margin +
                                 model_1$coef['gopleg']*voterid2$gopleg)

# test that we did it right
voterid2$pprob_test <- voterid2$pprob - voterid2$pprob_manual
summary(voterid2$pprob_test) # should be zeros

#######1. calculate average effect of photo using observed values----
voterid2$pprob_gopleg_upsd <- pnorm(model_1$coef['(Intercept)'] + 
                                 model_1$coef['fraud']*voterid2$fraud + 
                                 model_1$coef['election_margin']*voterid2$election_margin + 
                                 model_1$coef['gopleg']*gopleg_obs_high)
summary(voterid2$pprob_gopleg_upsd)

voterid2$pprob_gopleg_downsd <- pnorm(model_1$coef['(Intercept)'] + 
                                 model_1$coef['fraud']*voterid2$fraud + 
                                 model_1$coef['election_margin']*voterid2$election_margin + 
                                 model_1$coef['gopleg']*gopleg_obs_low)
summary(voterid2$pprob_gopleg_downsd)

voterid2$pprob_effect <- voterid2$pprob_gopleg_upsd - voterid2$pprob_gopleg_downsd
summary(voterid2$pprob_effect)	
```

Summary:  Interpreting the Coefficients, include the AIC

```{r note to self, echo=TRUE, results='asis'}
stargazer(model_1, header = F)
```

